version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/api'
    update_schedule: 'weekly'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'all'
      - match:
          dependency_type: 'production'
          update_type: 'semver:minor'
  - package_manager: 'javascript'
    directory: '/web'
    update_schedule: 'weekly'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'all'
      - match:
          dependency_type: 'production'
          update_type: 'semver:minor'
