name: Web
on:
  push:
    paths:
      - web/*
  pull_request:
    paths:
      - web/*
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn --cwd web install
      - name: Test
        run: yarn --cwd web test
        env:
          CI: true
      - name: Upload coverage
        run: cat ./web/coverage/lcov.info | npx codacy-coverage
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
